extends Node

var PLAYER_CONTROLS_ACTIVE = true setget set_PLAYER_CONTROLS_ACTIVE
var CAMERA_CONTROLS_ACTIVE = true setget set_CAMERA_CONTROLS_ACTIVE


func set_CAMERA_CONTROLS_ACTIVE(value):
	CAMERA_CONTROLS_ACTIVE = value


func set_PLAYER_CONTROLS_ACTIVE(value):
	PLAYER_CONTROLS_ACTIVE = value

